import Head from 'next/head'
const About = () => {
    return (
      <>
      <Head>
        <title>About</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
     <div>
        <h1>About</h1>
        <p>Fake user list adapted from this youtube tutorial series. </p>
        <iframe width="560" height="315" src="https://www.youtube.com/embed/A63UxsQsEbU" title="YouTube video player"  allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
     </div>
     <div>
        <p>Recipe list DjangoRestAPI is hosted at <a href="https://gregprojects.fly.dev/recipes/">fly.io</a>  </p>
        <iframe width="560" height="315" src="https://www.youtube.com/embed/IXfUGd_A1sc" title="YouTube video player"  allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
     </div>
     </>
      );
}
 
export default About;