import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Link from 'next/link'
import Image from 'next/image'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      <h1 className ={styles.title}>Homepage</h1>
      <Link href={'/placeholder-json/users'} >
          <a className={styles.single}>
            <h3>List of Fake People</h3>
          </a>
      </Link>
      <p>From https://jsonplaceholder.typicode.com/</p>
      
      <Link href={'greg-recipes/recipe-list'} >
          <a className={styles.single}>
            <h3>Recipes from Gregs DjangoRestAPI</h3>
          </a>
      </Link>
      <p>Recipes fetched from Django RestAPI on fly.io</p>
      <Image src="/../public/images/apiFetchCode.png" alt="site logo" width={350} height={100} />

      
    </div>
  )
}
